name: Node CI

on: [push]

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - uses: "docker://node:12"
      with:
        cmd: invalid
    - uses: "docker://node:12"
      with:
        cmd: yarn workspace @fndebrid/electron-main compile
    - uses: "docker://node:12"
      with:
        cmd: yarn workspace @fndebrid/electron-renderer compile
